### ISSUE TITLE
Typo in the Lab #2 Gradient Descent

### ISSUE THREAD

**Issue by masterugwee** [giladgressel/cyber_machine_learning#1]
The text was supposed to be squared_error , it's given as squared_loss. I checked your previous commits, two of them were fixed but I guess this got away. 

[Link to the line.](https://github.com/giladgressel/cyber_machine_learning/blame/5a63053e8894f9564cdc2589eb0bcecb605cd06e/ML_notebooks/002_linear_regression_gradient_descent_regularization.ipynb#L154)

**Comment by giladgressel** [comment]
thx, in future would love a PR 😀

**Comment by masterugwee** [comment]
Sure!
